#!/usr/bin/env bash

DIR_DEVICE="/sdcard/Android/data/de.holeschak.bmw_deep_obd/files/Configurations"

mapfile -t ARRAY_FILES < <(find . -type f -iname '*.cccfg' -o -iname '*.ccpage' -o -iname '*.ccpages' -o -iname '*.cs' -o -iname '*.xsd' -o -iname '*.xml' | sort | sed 's/^\.\///g')


pull() {
	for FILE in "${ARRAY_FILES[@]}"; do
		adb pull "${DIR_DEVICE}/${FILE}" "${FILE}"
	done
}

push() {
	# TODO: Yeah, there's a better way, I know
	adb shell "find ${DIR_DEVICE} -type f -iname '*.cccfg'   -exec rm {} \\;"
	adb shell "find ${DIR_DEVICE} -type f -iname '*.ccpage'  -exec rm {} \\;"
	adb shell "find ${DIR_DEVICE} -type f -iname '*.ccpages' -exec rm {} \\;"
	adb shell "find ${DIR_DEVICE} -type f -iname '*.cs'      -exec rm {} \\;"
	adb shell "find ${DIR_DEVICE} -type f -iname '*.xml'     -exec rm {} \\;"
	adb shell "find ${DIR_DEVICE} -type f -iname '*.xsd'     -exec rm {} \\;"

	for FILE in "${ARRAY_FILES[@]}"; do
		adb push "${FILE}" "${DIR_DEVICE}/${FILE}"
	done
}


"${1-pull}"
